### ISSUE TITLE
link broken?

### ISSUE THREAD

**Issue by zhanxw** [blengerich/Personalized_Regression#1]
Link to https://www.cs.cmu.edu/~blengeri/downloads/personalized_regression_ismb_2018.pdf is not working at this moment.

**Comment by blengerich** [comment]
Thanks for catching this! The link has been updated now.

Also, I've added a link to [new slides with more experimental results](https://www.cs.cmu.edu/~blengeri/downloads/slides/personalized_regression_psu.pdf).

FYI, we are planning to release a pretty major update of this method in the near future. The new slides hint at these changes; feel free to reach out to me if you are interested to hear more.

**Comment by zhanxw** [comment]
Thanks. In a typical regression setting:

y1 = x1 * b1 + e1
y2 = x2 * b2 + e2

If we set b1 = b2 and x1 != x2, will personalized regression give the same estimation for \hat{b1} and \hat{b2}? I am curious why "similarity in parameters is related to similarity in covariates" (copied from the bioinformatics publication).

**Comment by blengerich** [comment]
Personalized regression needs covariates to be meaningful. In this example, if there are covariates u1 = u2, then we should indeed have \hat{b1} = \hat{b2}.

Otherwise, if there are covariates u1 != u2, then we should find b1 != b2 such that d_b(\hat{b1}, \hat{b2}) = d_u(u1, u2). Where d_b() is a distance function over regression parameters, and d_u() is 
 a distance function over covariates.

This is not well-defined for only one pairwise constraint, but with more samples it becomes more constrained.
